apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configuration
data:
  prometheus.yaml: |- 
    global:
      evaluation_interval: 1m
      scrape_interval: 10s
      scrape_timeout: 10s
    scrape_configs:
    - job_name: kuma-controlplanes
      static_configs:
      - targets:
        - kuma-control-plane-metrics.kuma-system:5680
