apiVersion: v1
kind: Service
metadata:
  name: logging-collector
  labels:
    app: logging-collector
    component: logging-collector
spec:
  ports:
  - name: grpc
    protocol: TCP
    port: 4317
    targetPort: 4317
  - name: tcplog
    protocol: TCP
    port: 29018
    targetPort: 29018
  selector:
   app.kubernetes.io/name: logging-collector
