apiVersion: v1
kind: Service
metadata:
  name: trace-collector
  labels:
    app: trace-collector
    component: trace-collector
spec:
  ports:
  - name: grpc
    protocol: TCP
    port: 4317
    targetPort: 4317
  - name: zipkin
    protocol: TCP
    port: 9411
    targetPort: 9411
  selector:
   app.kubernetes.io/name: trace-collector
