apiVersion: v1
kind: Service
metadata:
  name: metrics-collector
  labels:
    app: metrics-collector
    component: metrics-collector
spec:
  ports:
  - name: otlp # Default endpoint for OpenTelemetry receiver.
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: metrics # Default endpoint for querying metrics.
    port: 8888
  selector:
   app.kubernetes.io/name: metrics-collector
