name: Build otel metrics zones helm chart

on:
  workflow_dispatch:

env:
  ACR_NAME:  mskmeshsharedgcore.azurecr.io
  ACR_REPO_NAME: otel-metrics-zones

jobs:
  build:
    name: publish acr
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
        name: checkout repo
      
      - name: install helm
        uses: Azure/setup-helm@v1
        with:
          version: latest
      - name: login to acr using helm
        run: |
          echo ${{ secrets.DESTINATION_REGISTRY_PASSWORD_MESH}} | helm registry login mskmeshsharedgcore.azurecr.io --username ${{ secrets.DESTINATION_REGISTRY_USERNAME_MESH }} --password-stdin

      - name: save helm chart to local registry
        run: |
          cd $GITHUB_WORKSPACE/charts/otel-metrics-zones/
          helm package .
      
      - name: publish chart to acr
        run: |
          helm push $GITHUB_WORKSPACE/charts/otel-metrics-zones/*.tgz  oci://mskmeshsharedgcore.azurecr.io     